{
 "title": "Purchases Dashboard",
 "time": { "from": "2025-06-26T00:00:00.000Z", "to": "2025-09-24T00:00:00.000Z" },
 "panels": [
  {
   "title": "Покупки по дням",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    toStartOfDay(purchase_datetime) AS time,\r\n    count() AS value\r\nFROM piccha.purchases\r\nGROUP BY time\r\nORDER BY time\r\n"
    }
   ]
  },
  {
   "title": "Всего покупок",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count() AS value\r\nFROM piccha.purchases\r\n"
    }
   ]
  },
  {
   "title": "Продажи по магазинам",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  s.store_name,\r\n  sum(p.total_amount) AS revenue\r\nFROM piccha.purchases p\r\nJOIN piccha.stores s ON p.store_id = s.store_id\r\nGROUP BY s.store_name\r\nORDER BY revenue DESC\r\n"
    }
   ]
  },
  {
   "title": "Количество магазинов",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count() AS value\r\nFROM piccha.stores\r\n"
    }
   ]
  },
  {
   "title": "Топ-10 магазинов по выручке",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    p.store_id,\r\n    s.store_name,\r\n    sum(p.total_amount) AS revenue,\r\n    count() AS purchases\r\nFROM piccha.purchases AS p\r\nJOIN piccha.stores AS s ON p.store_id = s.store_id\r\nGROUP BY p.store_id, s.store_name\r\nORDER BY revenue DESC\r\nLIMIT 10;\r\n"
    }
   ]
  },
  {
   "title": "Распределение по полу",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  gender,\r\n  count() AS cnt\r\nFROM piccha.customers\r\nGROUP BY gender\r\n"
    }
   ]
  }
 ]
}